### ISSUE TITLE
feature improvement: firstpass report for C++ and Java application

### ISSUE THREAD

**Issue by pjhwa** [pjhwa/dumpdocker#8]
At the current stage, the firstpass report can make report for C application. But many applications are made in C++ and Java these days. So, it will very helpful if we can get the firstpass report from C++ and Java application core files.

**Comment by YounghunChung** [comment]
Good idea!!! 

I would like to contribute.

**Comment by pjhwa** [comment]
Thanks, Younghun. 👍
